name = "AddPackage"
uuid = "70d26913-0580-4037-ad67-7d2c365cf5c5"
authors = ["Robert Moss <mossr@cs.stanford.edu>"]
version = "0.1.1"

[deps]
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"

[compat]
julia = "1"

[extras]
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Pkg", "Test"]
